# Generated by Django 5.0.7 on 2024-08-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('deparment', models.CharField(max_length=50)),
                ('deatOfJoining', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('projectDomain', models.CharField(max_length=30)),
            ],
        ),
    ]
